@startuml 並列処理
title フォークで並列処理
start
:米を研ぐ;

fork
:具材を切る;
:肉を炒める;
:玉ねぎを炒める;
:人参を炒める;
:水を入れる;
:ジャガイモを入れる;
fork
:具に火が通るまで煮込む;
fork again
:不要な調理器具を洗う;
:皿を用意する;
end fork
:あくを取る;
:ルーを入れて混ぜる;
:カレー]
fork again
:米を炊く;
:ライス]
end fork
:ご飯を皿に盛る;
:カレーを盛る;

:カレーライス]
stop
@enduml