@startuml 演習6-3
state メニュー
state 予約と確認
state あなたの順番
state 今の順番

[*] -> メニュー
メニュー -down-> 予約と確認:予約と確認ボタンを押す
予約と確認 -up-> メニュー:取消ボタンをおす
予約と確認 -> あなたの順番:登録ボタンを押す
予約と確認 -> あなたの順番:確認ボタンを押す
あなたの順番 -up-> メニュー:メニューボタンをおす
今の順番 -up-> メニュー:メニューボタンをおす
メニュー -down-> 今の順番:今の順番ボタンを押す
メニュー -> [*]

@enduml