@startuml 演習6-5-3
state 電源OFF
state 電源ON{
    state 右旋回:右モータOFF 左モータON 
    state 左旋回:右モータON 左モータOFF
}

電源OFF -> 電源ON :SWを入れる
電源OFF <- 電源ON :SWを切る
左旋回 -> 右旋回 :光センサーがラインを外れる(「暗い」と判断)
左旋回 <- 右旋回 :光センサーがラインに乗る(「明るい」と判断)
@enduml