@startuml 演習3-2 
left to right direction
class 医師 {
---
+ 診察する()
+ 診察記録を作成する()
}
class 患者{
---
}
class 医局 {
    
}
class 診察記録 {
    
}
医師 "1制作者" ---> "制作物*" 診察記録:作成する
医師 "1担当医" ---> "患者*" 患者:担当する
医局 "1" <-right- "*" 医師:所属する
患者 "1"---"*"診察記録
@enduml
