@startuml 商品を注文する
hide footbox
'メッセージに自動で番号を降る
autonumber
' 厳密なUMLに準拠する
skinparam style strictuml

Actor "<u>:会員</u>" as member
participant "<u>:商品検索画面</u>" as boundary <<boundary>>
participant "<u>:商品検索コントローラ</u>" as controller <<controller>>


mainframe sd 商品を注文する 

member -> boundary : 商品情報を検索する()
    activate  boundary
    boundary -> controller : 商品情報を検索する(商品番号)
        activate controller
            create  "<u>:商品</u>" as goods <<entity>>
            controller --> goods : 生成()　<<create>>
            loop 0,カテゴリ数
                create  "<u>:商品カテゴリ</u>" as cate <<entity>>
                controller --> cate : 生成() <<create>>
                    controller -> cate : カテゴリを設定する
            end loop
            boundary <-- controller : 商品情報
        deactivate controller
    boundary -> boundary : 商品情報を表示(商品情報)    
    member <-- boundary : 商品情報
deactivate boundary

@enduml